## `src/executor/interface/ExecutorError` (Module)

**Type:** `unknown`

---

### `ExecutorError` (Class)

**Type:** `unknown`

Custom error class for executor operations.

This class provides a structured way to handle errors that occur during executor operations.
It extends the standard Error class to include an error identification string, which can be used
to categorize and manage errors more effectively.

**Example:**

```typescript
try {
  // some executor operation
} catch (error) {
  throw new ExecutorError('EXECUTOR_ERROR', error);
}
```

**Example:**

create an error with a message from a string

```typescript
const error = new ExecutorError('ERROR_ID', 'This is an error message');

// => error.message is 'This is an error message'
// => error.id is 'ERROR_ID'
```

---

#### `new ExecutorError` (Constructor)

**Type:** `(id: string, originalError: string \| Error) => ExecutorError`

#### Parameters

| Name                        | Type              | Optional | Default | Since | Deprecated | Description                                                              |
| --------------------------- | ----------------- | -------- | ------- | ----- | ---------- | ------------------------------------------------------------------------ |
| `id`                        | `string`          | ❌       | -       | -     | -          | A unique identifier for the error, used for categorization and tracking. |
| `originalError`             | `string \| Error` | ✅       | -       | -     | -          | The original error message or Error object that triggered this error.    |
| This parameter is optional. |

---

#### `cause` (Property)

**Type:** `unknown`

---

#### `id` (Property)

**Type:** `string`

A unique identifier for the error, used for categorization and tracking.

---

#### `message` (Property)

**Type:** `string`

---

#### `name` (Property)

**Type:** `string`

---

#### `stack` (Property)

**Type:** `string`

---

#### `stackTraceLimit` (Property)

**Type:** `number`

The
`Error.stackTraceLimit`
property specifies the number of stack frames
collected by a stack trace (whether generated by
`new Error().stack`
or

`Error.captureStackTrace(obj)`
).

The default value is
`10`
but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

---

#### `captureStackTrace` (Method)

**Type:** `(targetObject: object, constructorOpt: Function) => void`

#### Parameters

| Name             | Type       | Optional | Default | Since | Deprecated | Description |
| ---------------- | ---------- | -------- | ------- | ----- | ---------- | ----------- |
| `targetObject`   | `object`   | ❌       | -       | -     | -          |             |
| `constructorOpt` | `Function` | ✅       | -       | -     | -          |             |

---

##### `captureStackTrace` (CallSignature)

**Type:** `void`

Creates a
`.stack`
property on
`targetObject`
, which when accessed returns
a string representing the location in the code at which

`Error.captureStackTrace()`
was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack; // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with

`${myObject.name}: ${myObject.message}`
.

The optional
`constructorOpt`
argument accepts a function. If given, all frames
above
`constructorOpt`
, including
`constructorOpt`
, will be omitted from the
generated stack trace.

The
`constructorOpt`
argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

| Name             | Type       | Optional | Default | Since | Deprecated | Description |
| ---------------- | ---------- | -------- | ------- | ----- | ---------- | ----------- |
| `targetObject`   | `object`   | ❌       | -       | -     | -          |             |
| `constructorOpt` | `Function` | ✅       | -       | -     | -          |             |

---

#### `prepareStackTrace` (Method)

**Type:** `(err: Error, stackTraces: CallSite[]) => any`

#### Parameters

| Name          | Type         | Optional | Default | Since | Deprecated | Description |
| ------------- | ------------ | -------- | ------- | ----- | ---------- | ----------- |
| `err`         | `Error`      | ❌       | -       | -     | -          |             |
| `stackTraces` | `CallSite[]` | ❌       | -       | -     | -          |             |

---

##### `prepareStackTrace` (CallSignature)

**Type:** `any`

**See:**

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Parameters

| Name          | Type         | Optional | Default | Since | Deprecated | Description |
| ------------- | ------------ | -------- | ------- | ----- | ---------- | ----------- |
| `err`         | `Error`      | ❌       | -       | -     | -          |             |
| `stackTraces` | `CallSite[]` | ❌       | -       | -     | -          |             |

---
